[2025-02-19T11:49:42.400+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-19T11:49:42.413+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline.save_data manual__2025-02-19T11:49:28.025552+00:00 [queued]>
[2025-02-19T11:49:42.520+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline.save_data manual__2025-02-19T11:49:28.025552+00:00 [queued]>
[2025-02-19T11:49:42.521+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-19T11:49:42.528+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): save_data> on 2025-02-19 11:49:28.025552+00:00
[2025-02-19T11:49:42.532+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=432) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-19T11:49:42.532+0000] {standard_task_runner.py:72} INFO - Started process 434 to run task
[2025-02-19T11:49:42.533+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pipeline', 'save_data', 'manual__2025-02-19T11:49:28.025552+00:00', '--job-id', '947', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp24a3byi8']
[2025-02-19T11:49:42.534+0000] {standard_task_runner.py:105} INFO - Job 947: Subtask save_data
[2025-02-19T11:49:42.560+0000] {task_command.py:467} INFO - Running <TaskInstance: pipeline.save_data manual__2025-02-19T11:49:28.025552+00:00 [running]> on host 23903a4a7553
[2025-02-19T11:49:42.630+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pipeline' AIRFLOW_CTX_TASK_ID='save_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-19T11:49:28.025552+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-19T11:49:28.025552+00:00'
[2025-02-19T11:49:42.630+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-19T11:49:42.631+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-19T11:49:42.631+0000] {logging_mixin.py:190} INFO - Current task name:save_data state:running start_date:2025-02-19 11:49:42.415763+00:00
[2025-02-19T11:49:42.631+0000] {logging_mixin.py:190} INFO - Dag name:pipeline and current dag run status:running
[2025-02-19T11:49:42.631+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-19T11:49:42.632+0000] {safe_data.py:23} INFO - Starting to save data with 10 records.
[2025-02-19T11:49:42.633+0000] {safe_data.py:25} INFO - final df:                                               Review
0  Я мама двух маленьких детей, и постоянная уста...
1  Недостатки: Не помогло. все время была сонливо...
2  Я начала принимать Проспекту при астении по ре...
3  Давненько хотела пропить что-то для улучшения ...
4  Не знаю, что бы делала, если бы не узнала про ...
5  Брали Проспекту дедушке, для улучшения памяти....
6  Хвалю Проспекту, отлично помогает при СДВГ у р...
7  Проспекту назначили папе после инсульта, у нег...
8  Давала эти таблетки сыну, а то его неусидчивос...
9  Искала хорошее средство для улучшения концентр...
[2025-02-19T11:49:42.634+0000] {safe_data.py:29} INFO - File ../temp_file_for_data.json does not exist. Creating a new file.
[2025-02-19T11:49:42.634+0000] {safe_data.py:49} INFO - Added 10 new records to the existing data.
[2025-02-19T11:49:42.635+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/operators/safe_data.py", line 52, in save_data
    with open(file_path, 'w') as file:
         ^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '../temp_file_for_data.json'
[2025-02-19T11:49:42.640+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-19T11:49:42.641+0000] {logging_mixin.py:190} INFO - Task start:2025-02-19 11:49:42.415763+00:00 end:2025-02-19 11:49:42.640537+00:00 duration:0.224774
[2025-02-19T11:49:42.641+0000] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): save_data> dag:<DAG: pipeline> dagrun:<DagRun pipeline @ 2025-02-19 11:49:28.025552+00:00: manual__2025-02-19T11:49:28.025552+00:00, state:running, queued_at: 2025-02-19 11:49:28.043305+00:00. externally triggered: True>
[2025-02-19T11:49:42.641+0000] {logging_mixin.py:190} INFO - Failure caused by [Errno 13] Permission denied: '../temp_file_for_data.json'
[2025-02-19T11:49:42.641+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=pipeline, task_id=save_data, run_id=manual__2025-02-19T11:49:28.025552+00:00, execution_date=20250219T114928, start_date=20250219T114942, end_date=20250219T114942
[2025-02-19T11:49:42.654+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-19T11:49:42.654+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 947 for task save_data ([Errno 13] Permission denied: '../temp_file_for_data.json'; 434)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/operators/safe_data.py", line 52, in save_data
    with open(file_path, 'w') as file:
         ^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '../temp_file_for_data.json'
[2025-02-19T11:49:42.673+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-19T11:49:42.683+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-19T11:49:42.684+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
