[2025-02-19T21:17:15.890+0000] {processor.py:186} INFO - Started process (PID=31977) to work on /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:17:15.890+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/analitics/temp.py for tasks to queue
[2025-02-19T21:17:15.892+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:17:15.891+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:17:15.897+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:17:15.896+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/analitics/temp.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/analitics/temp.py", line 7, in <module>
    from dags.operators.analitics.yandexGPTdemo import get_response
ModuleNotFoundError: No module named 'dags'
[2025-02-19T21:17:15.897+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:17:15.920+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/analitics/temp.py took 0.035 seconds
[2025-02-19T21:17:46.305+0000] {processor.py:186} INFO - Started process (PID=32043) to work on /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:17:46.306+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/analitics/temp.py for tasks to queue
[2025-02-19T21:17:46.307+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:17:46.307+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:17:46.311+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:17:46.310+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/analitics/temp.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/analitics/temp.py", line 7, in <module>
    from dags.operators.analitics.yandexGPTdemo import get_response
ModuleNotFoundError: No module named 'dags'
[2025-02-19T21:17:46.312+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:17:46.326+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/analitics/temp.py took 0.027 seconds
[2025-02-19T21:18:16.547+0000] {processor.py:186} INFO - Started process (PID=32109) to work on /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:18:16.549+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/analitics/temp.py for tasks to queue
[2025-02-19T21:18:16.552+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:18:16.552+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:18:16.562+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:18:16.560+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/analitics/temp.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/analitics/temp.py", line 7, in <module>
    from dags.operators.analitics.yandexGPTdemo import get_response
ModuleNotFoundError: No module named 'dags'
[2025-02-19T21:18:16.563+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:18:16.582+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/analitics/temp.py took 0.050 seconds
[2025-02-19T21:18:46.656+0000] {processor.py:186} INFO - Started process (PID=32175) to work on /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:18:46.658+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/analitics/temp.py for tasks to queue
[2025-02-19T21:18:46.660+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:18:46.659+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:18:46.667+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:18:46.666+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/analitics/temp.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/analitics/temp.py", line 7, in <module>
    from dags.operators.analitics.yandexGPTdemo import get_response
ModuleNotFoundError: No module named 'dags'
[2025-02-19T21:18:46.668+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:18:46.690+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/analitics/temp.py took 0.045 seconds
[2025-02-19T21:19:16.813+0000] {processor.py:186} INFO - Started process (PID=32241) to work on /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:19:16.815+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/analitics/temp.py for tasks to queue
[2025-02-19T21:19:16.816+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:19:16.816+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:19:16.822+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:19:16.821+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/analitics/temp.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/analitics/temp.py", line 7, in <module>
    from dags.operators.analitics.yandexGPTdemo import get_response
ModuleNotFoundError: No module named 'dags'
[2025-02-19T21:19:16.822+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:19:16.837+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/analitics/temp.py took 0.032 seconds
[2025-02-19T21:19:47.159+0000] {processor.py:186} INFO - Started process (PID=32307) to work on /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:19:47.162+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/analitics/temp.py for tasks to queue
[2025-02-19T21:19:47.164+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:19:47.164+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:19:47.175+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:19:47.173+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/analitics/temp.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/analitics/temp.py", line 7, in <module>
    from dags.operators.analitics.yandexGPTdemo import get_response
ModuleNotFoundError: No module named 'dags'
[2025-02-19T21:19:47.176+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:19:47.197+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/analitics/temp.py took 0.056 seconds
[2025-02-19T21:20:17.440+0000] {processor.py:186} INFO - Started process (PID=32372) to work on /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:20:17.442+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/analitics/temp.py for tasks to queue
[2025-02-19T21:20:17.443+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:20:17.442+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:20:17.448+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:20:17.447+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/analitics/temp.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/analitics/temp.py", line 7, in <module>
    from dags.operators.analitics.yandexGPTdemo import get_response
ModuleNotFoundError: No module named 'dags'
[2025-02-19T21:20:17.448+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:20:17.469+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/analitics/temp.py took 0.035 seconds
[2025-02-19T21:20:47.697+0000] {processor.py:186} INFO - Started process (PID=32438) to work on /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:20:47.698+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/analitics/temp.py for tasks to queue
[2025-02-19T21:20:47.699+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:20:47.699+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:20:47.703+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:20:47.702+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/analitics/temp.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/analitics/temp.py", line 7, in <module>
    from dags.operators.analitics.yandexGPTdemo import get_response
ModuleNotFoundError: No module named 'dags'
[2025-02-19T21:20:47.703+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:20:47.716+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/analitics/temp.py took 0.025 seconds
[2025-02-19T21:21:18.228+0000] {processor.py:186} INFO - Started process (PID=32504) to work on /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:21:18.230+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/analitics/temp.py for tasks to queue
[2025-02-19T21:21:18.234+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:21:18.233+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:21:18.244+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:21:18.242+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/analitics/temp.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/analitics/temp.py", line 7, in <module>
    from dags.operators.analitics.yandexGPTdemo import get_response
ModuleNotFoundError: No module named 'dags'
[2025-02-19T21:21:18.245+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:21:18.292+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/analitics/temp.py took 0.078 seconds
[2025-02-19T21:21:48.494+0000] {processor.py:186} INFO - Started process (PID=32570) to work on /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:21:48.499+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/analitics/temp.py for tasks to queue
[2025-02-19T21:21:48.503+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:21:48.502+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:21:48.511+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:21:48.509+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/analitics/temp.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/analitics/temp.py", line 7, in <module>
    from dags.operators.analitics.yandexGPTdemo import get_response
ModuleNotFoundError: No module named 'dags'
[2025-02-19T21:21:48.511+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:21:48.534+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/analitics/temp.py took 0.051 seconds
[2025-02-19T21:22:19.027+0000] {processor.py:186} INFO - Started process (PID=32636) to work on /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:22:19.029+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/analitics/temp.py for tasks to queue
[2025-02-19T21:22:19.031+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:22:19.030+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:22:19.038+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:22:19.036+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/analitics/temp.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/analitics/temp.py", line 7, in <module>
    from dags.operators.analitics.yandexGPTdemo import get_response
ModuleNotFoundError: No module named 'dags'
[2025-02-19T21:22:19.038+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:22:19.062+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/analitics/temp.py took 0.043 seconds
[2025-02-19T21:22:46.483+0000] {processor.py:186} INFO - Started process (PID=32702) to work on /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:22:46.484+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/analitics/temp.py for tasks to queue
[2025-02-19T21:22:46.486+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:22:46.485+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:22:46.495+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:22:46.494+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/analitics/temp.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/analitics/temp.py", line 7, in <module>
    from dags.operators.analitics.yandexGPTdemo import get_response
ModuleNotFoundError: No module named 'dags'
[2025-02-19T21:22:46.496+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:22:46.516+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/analitics/temp.py took 0.041 seconds
[2025-02-19T21:23:17.287+0000] {processor.py:186} INFO - Started process (PID=32768) to work on /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:23:17.289+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/analitics/temp.py for tasks to queue
[2025-02-19T21:23:17.290+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:23:17.290+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:23:17.297+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:23:17.296+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/analitics/temp.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/analitics/temp.py", line 7, in <module>
    from dags.operators.analitics.yandexGPTdemo import get_response
ModuleNotFoundError: No module named 'dags'
[2025-02-19T21:23:17.298+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:23:17.320+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/analitics/temp.py took 0.041 seconds
[2025-02-19T21:23:48.011+0000] {processor.py:186} INFO - Started process (PID=32834) to work on /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:23:48.013+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/analitics/temp.py for tasks to queue
[2025-02-19T21:23:48.014+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:23:48.014+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:23:48.020+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:23:48.019+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/analitics/temp.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/analitics/temp.py", line 7, in <module>
    from dags.operators.analitics.yandexGPTdemo import get_response
ModuleNotFoundError: No module named 'dags'
[2025-02-19T21:23:48.020+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:23:48.037+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/analitics/temp.py took 0.034 seconds
[2025-02-19T21:24:18.231+0000] {processor.py:186} INFO - Started process (PID=32900) to work on /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:24:18.232+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/analitics/temp.py for tasks to queue
[2025-02-19T21:24:18.234+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:24:18.233+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:24:18.241+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:24:18.240+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/analitics/temp.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/analitics/temp.py", line 7, in <module>
    from dags.operators.analitics.yandexGPTdemo import get_response
ModuleNotFoundError: No module named 'dags'
[2025-02-19T21:24:18.242+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:24:18.259+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/analitics/temp.py took 0.034 seconds
[2025-02-19T21:24:48.293+0000] {processor.py:186} INFO - Started process (PID=32966) to work on /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:24:48.294+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/analitics/temp.py for tasks to queue
[2025-02-19T21:24:48.295+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:24:48.294+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:24:48.300+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:24:48.299+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/analitics/temp.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/analitics/temp.py", line 7, in <module>
    from dags.operators.analitics.yandexGPTdemo import get_response
ModuleNotFoundError: No module named 'dags'
[2025-02-19T21:24:48.300+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:24:48.318+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/analitics/temp.py took 0.031 seconds
[2025-02-19T21:25:19.219+0000] {processor.py:186} INFO - Started process (PID=33032) to work on /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:25:19.220+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/analitics/temp.py for tasks to queue
[2025-02-19T21:25:19.220+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:25:19.220+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:25:19.224+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:25:19.224+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/analitics/temp.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/analitics/temp.py", line 7, in <module>
    from dags.operators.analitics.yandexGPTdemo import get_response
ModuleNotFoundError: No module named 'dags'
[2025-02-19T21:25:19.225+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:25:19.236+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/analitics/temp.py took 0.021 seconds
[2025-02-19T21:25:49.367+0000] {processor.py:186} INFO - Started process (PID=33098) to work on /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:25:49.370+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/analitics/temp.py for tasks to queue
[2025-02-19T21:25:49.373+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:25:49.372+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:25:49.383+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:25:49.380+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/analitics/temp.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/analitics/temp.py", line 7, in <module>
    from dags.operators.analitics.yandexGPTdemo import get_response
ModuleNotFoundError: No module named 'dags'
[2025-02-19T21:25:49.383+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:25:49.406+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/analitics/temp.py took 0.049 seconds
[2025-02-19T21:26:19.484+0000] {processor.py:186} INFO - Started process (PID=33164) to work on /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:26:19.486+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/analitics/temp.py for tasks to queue
[2025-02-19T21:26:19.487+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:26:19.487+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:26:19.493+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:26:19.492+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/analitics/temp.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/analitics/temp.py", line 7, in <module>
    from dags.operators.analitics.yandexGPTdemo import get_response
ModuleNotFoundError: No module named 'dags'
[2025-02-19T21:26:19.493+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:26:19.512+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/analitics/temp.py took 0.035 seconds
[2025-02-19T21:26:50.138+0000] {processor.py:186} INFO - Started process (PID=33230) to work on /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:26:50.140+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/analitics/temp.py for tasks to queue
[2025-02-19T21:26:50.142+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:26:50.142+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:26:50.149+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:26:50.147+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/analitics/temp.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/analitics/temp.py", line 7, in <module>
    from dags.operators.analitics.yandexGPTdemo import get_response
ModuleNotFoundError: No module named 'dags'
[2025-02-19T21:26:50.149+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:26:50.163+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/analitics/temp.py took 0.034 seconds
[2025-02-19T21:27:20.556+0000] {processor.py:186} INFO - Started process (PID=33296) to work on /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:27:20.558+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/analitics/temp.py for tasks to queue
[2025-02-19T21:27:20.559+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:27:20.559+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:27:20.566+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:27:20.565+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/analitics/temp.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/analitics/temp.py", line 7, in <module>
    from dags.operators.analitics.yandexGPTdemo import get_response
ModuleNotFoundError: No module named 'dags'
[2025-02-19T21:27:20.567+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:27:20.585+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/analitics/temp.py took 0.037 seconds
[2025-02-19T21:27:50.833+0000] {processor.py:186} INFO - Started process (PID=33362) to work on /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:27:50.836+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/analitics/temp.py for tasks to queue
[2025-02-19T21:27:50.838+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:27:50.837+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:27:50.846+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:27:50.844+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/analitics/temp.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/analitics/temp.py", line 7, in <module>
    from dags.operators.analitics.yandexGPTdemo import get_response
ModuleNotFoundError: No module named 'dags'
[2025-02-19T21:27:50.847+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:27:50.868+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/analitics/temp.py took 0.044 seconds
[2025-02-19T21:28:21.121+0000] {processor.py:186} INFO - Started process (PID=33428) to work on /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:28:21.123+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/analitics/temp.py for tasks to queue
[2025-02-19T21:28:21.125+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:28:21.124+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:28:21.131+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:28:21.130+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/analitics/temp.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/analitics/temp.py", line 7, in <module>
    from dags.operators.analitics.yandexGPTdemo import get_response
ModuleNotFoundError: No module named 'dags'
[2025-02-19T21:28:21.132+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:28:21.147+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/analitics/temp.py took 0.034 seconds
[2025-02-19T21:28:51.457+0000] {processor.py:186} INFO - Started process (PID=33494) to work on /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:28:51.459+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/analitics/temp.py for tasks to queue
[2025-02-19T21:28:51.461+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:28:51.460+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:28:51.466+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:28:51.465+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/analitics/temp.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/analitics/temp.py", line 7, in <module>
    from dags.operators.analitics.yandexGPTdemo import get_response
ModuleNotFoundError: No module named 'dags'
[2025-02-19T21:28:51.466+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:28:51.483+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/analitics/temp.py took 0.033 seconds
[2025-02-19T21:29:21.784+0000] {processor.py:186} INFO - Started process (PID=33560) to work on /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:29:21.786+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/analitics/temp.py for tasks to queue
[2025-02-19T21:29:21.788+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:29:21.788+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:29:21.794+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:29:21.793+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/analitics/temp.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/analitics/temp.py", line 7, in <module>
    from dags.operators.analitics.yandexGPTdemo import get_response
ModuleNotFoundError: No module named 'dags'
[2025-02-19T21:29:21.795+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:29:21.817+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/analitics/temp.py took 0.043 seconds
[2025-02-19T21:29:52.024+0000] {processor.py:186} INFO - Started process (PID=33626) to work on /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:29:52.026+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/analitics/temp.py for tasks to queue
[2025-02-19T21:29:52.027+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:29:52.026+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:29:52.032+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:29:52.031+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/analitics/temp.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/analitics/temp.py", line 7, in <module>
    from dags.operators.analitics.yandexGPTdemo import get_response
ModuleNotFoundError: No module named 'dags'
[2025-02-19T21:29:52.033+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:29:52.053+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/analitics/temp.py took 0.037 seconds
[2025-02-19T21:30:22.320+0000] {processor.py:186} INFO - Started process (PID=33692) to work on /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:30:22.321+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/analitics/temp.py for tasks to queue
[2025-02-19T21:30:22.323+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:30:22.322+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:30:22.328+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:30:22.327+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/analitics/temp.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/analitics/temp.py", line 7, in <module>
    from dags.operators.analitics.yandexGPTdemo import get_response
ModuleNotFoundError: No module named 'dags'
[2025-02-19T21:30:22.329+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:30:22.348+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/analitics/temp.py took 0.036 seconds
[2025-02-19T21:30:52.916+0000] {processor.py:186} INFO - Started process (PID=33758) to work on /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:30:52.943+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/analitics/temp.py for tasks to queue
[2025-02-19T21:30:52.944+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:30:52.944+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:30:52.951+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:30:52.949+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/analitics/temp.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/analitics/temp.py", line 7, in <module>
    from dags.operators.analitics.yandexGPTdemo import get_response
ModuleNotFoundError: No module named 'dags'
[2025-02-19T21:30:52.951+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:30:52.965+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/analitics/temp.py took 0.058 seconds
[2025-02-19T21:31:23.609+0000] {processor.py:186} INFO - Started process (PID=33824) to work on /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:31:23.613+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/analitics/temp.py for tasks to queue
[2025-02-19T21:31:23.614+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:31:23.614+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:31:23.621+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:31:23.619+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/analitics/temp.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/analitics/temp.py", line 7, in <module>
    from dags.operators.analitics.yandexGPTdemo import get_response
ModuleNotFoundError: No module named 'dags'
[2025-02-19T21:31:23.621+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:31:23.641+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/analitics/temp.py took 0.042 seconds
[2025-02-19T21:31:54.048+0000] {processor.py:186} INFO - Started process (PID=33890) to work on /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:31:54.050+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/analitics/temp.py for tasks to queue
[2025-02-19T21:31:54.051+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:31:54.051+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:31:54.058+0000] {logging_mixin.py:190} INFO - [2025-02-19T21:31:54.056+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/analitics/temp.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/analitics/temp.py", line 7, in <module>
    from dags.operators.analitics.yandexGPTdemo import get_response
ModuleNotFoundError: No module named 'dags'
[2025-02-19T21:31:54.058+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/analitics/temp.py
[2025-02-19T21:31:54.083+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/analitics/temp.py took 0.042 seconds
