[2025-02-19T11:29:15.143+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-19T11:29:15.155+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline.consolidate_data manual__2025-02-19T11:29:09.845326+00:00 [queued]>
[2025-02-19T11:29:15.257+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline.consolidate_data manual__2025-02-19T11:29:09.845326+00:00 [queued]>
[2025-02-19T11:29:15.257+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-19T11:29:15.263+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): consolidate_data> on 2025-02-19 11:29:09.845326+00:00
[2025-02-19T11:29:15.267+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=113) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-19T11:29:15.268+0000] {standard_task_runner.py:72} INFO - Started process 115 to run task
[2025-02-19T11:29:15.268+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pipeline', 'consolidate_data', 'manual__2025-02-19T11:29:09.845326+00:00', '--job-id', '887', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpio8jd8tf']
[2025-02-19T11:29:15.269+0000] {standard_task_runner.py:105} INFO - Job 887: Subtask consolidate_data
[2025-02-19T11:29:15.291+0000] {task_command.py:467} INFO - Running <TaskInstance: pipeline.consolidate_data manual__2025-02-19T11:29:09.845326+00:00 [running]> on host 23903a4a7553
[2025-02-19T11:29:15.385+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pipeline' AIRFLOW_CTX_TASK_ID='consolidate_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-19T11:29:09.845326+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-19T11:29:09.845326+00:00'
[2025-02-19T11:29:15.385+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-19T11:29:15.386+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-19T11:29:15.386+0000] {logging_mixin.py:190} INFO - Current task name:consolidate_data state:running start_date:2025-02-19 11:29:15.155964+00:00
[2025-02-19T11:29:15.386+0000] {logging_mixin.py:190} INFO - Dag name:pipeline and current dag run status:running
[2025-02-19T11:29:15.386+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-19T11:29:15.387+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/operators/consolidate_date.py", line 10, in consolidate_data
    return pd.concat([df1, df2, df3])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/reshape/concat.py", line 382, in concat
    op = _Concatenator(
         ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/reshape/concat.py", line 448, in __init__
    ndims = self._get_ndims(objs)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/reshape/concat.py", line 489, in _get_ndims
    raise TypeError(msg)
TypeError: cannot concatenate object of type '<class 'str'>'; only Series and DataFrame objs are valid
[2025-02-19T11:29:15.394+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-19T11:29:15.394+0000] {logging_mixin.py:190} INFO - Task start:2025-02-19 11:29:15.155964+00:00 end:2025-02-19 11:29:15.394105+00:00 duration:0.238141
[2025-02-19T11:29:15.394+0000] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): consolidate_data> dag:<DAG: pipeline> dagrun:<DagRun pipeline @ 2025-02-19 11:29:09.845326+00:00: manual__2025-02-19T11:29:09.845326+00:00, state:running, queued_at: 2025-02-19 11:29:09.866940+00:00. externally triggered: True>
[2025-02-19T11:29:15.394+0000] {logging_mixin.py:190} INFO - Failure caused by cannot concatenate object of type '<class 'str'>'; only Series and DataFrame objs are valid
[2025-02-19T11:29:15.394+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=pipeline, task_id=consolidate_data, run_id=manual__2025-02-19T11:29:09.845326+00:00, execution_date=20250219T112909, start_date=20250219T112915, end_date=20250219T112915
[2025-02-19T11:29:15.408+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-19T11:29:15.408+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 887 for task consolidate_data (cannot concatenate object of type '<class 'str'>'; only Series and DataFrame objs are valid; 115)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/operators/consolidate_date.py", line 10, in consolidate_data
    return pd.concat([df1, df2, df3])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/reshape/concat.py", line 382, in concat
    op = _Concatenator(
         ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/reshape/concat.py", line 448, in __init__
    ndims = self._get_ndims(objs)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/reshape/concat.py", line 489, in _get_ndims
    raise TypeError(msg)
TypeError: cannot concatenate object of type '<class 'str'>'; only Series and DataFrame objs are valid
[2025-02-19T11:29:15.454+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-19T11:29:15.516+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-19T11:29:15.523+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
