[2025-02-19T11:32:04.866+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-19T11:32:04.878+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline.save_data manual__2025-02-19T11:31:58.817126+00:00 [queued]>
[2025-02-19T11:32:04.975+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline.save_data manual__2025-02-19T11:31:58.817126+00:00 [queued]>
[2025-02-19T11:32:04.975+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-19T11:32:04.983+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): save_data> on 2025-02-19 11:31:58.817126+00:00
[2025-02-19T11:32:04.987+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=182) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-19T11:32:04.988+0000] {standard_task_runner.py:72} INFO - Started process 184 to run task
[2025-02-19T11:32:04.988+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pipeline', 'save_data', 'manual__2025-02-19T11:31:58.817126+00:00', '--job-id', '892', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmplgei1vw0']
[2025-02-19T11:32:04.989+0000] {standard_task_runner.py:105} INFO - Job 892: Subtask save_data
[2025-02-19T11:32:05.015+0000] {task_command.py:467} INFO - Running <TaskInstance: pipeline.save_data manual__2025-02-19T11:31:58.817126+00:00 [running]> on host 23903a4a7553
[2025-02-19T11:32:05.085+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pipeline' AIRFLOW_CTX_TASK_ID='save_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-19T11:31:58.817126+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-19T11:31:58.817126+00:00'
[2025-02-19T11:32:05.086+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-19T11:32:05.086+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-19T11:32:05.087+0000] {logging_mixin.py:190} INFO - Current task name:save_data state:running start_date:2025-02-19 11:32:04.878650+00:00
[2025-02-19T11:32:05.087+0000] {logging_mixin.py:190} INFO - Dag name:pipeline and current dag run status:running
[2025-02-19T11:32:05.087+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-19T11:32:05.087+0000] {safe_data.py:23} INFO - Начинаем сохранить данные.
[2025-02-19T11:32:05.088+0000] {safe_data.py:33} INFO - Читаем данные из файла: temp_file_for_data.txt
[2025-02-19T11:32:05.088+0000] {safe_data.py:37} INFO - Данные успешно считаны из файла.
[2025-02-19T11:32:05.088+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/operators/safe_data.py", line 44, in save_data
    data.extend(parsed_data)  # Пример объединения, вам может понадобиться адаптировать логику
                ^^^^^^^^^^^
NameError: name 'parsed_data' is not defined
[2025-02-19T11:32:05.096+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-19T11:32:05.096+0000] {logging_mixin.py:190} INFO - Task start:2025-02-19 11:32:04.878650+00:00 end:2025-02-19 11:32:05.095944+00:00 duration:0.217294
[2025-02-19T11:32:05.096+0000] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): save_data> dag:<DAG: pipeline> dagrun:<DagRun pipeline @ 2025-02-19 11:31:58.817126+00:00: manual__2025-02-19T11:31:58.817126+00:00, state:running, queued_at: 2025-02-19 11:31:58.829725+00:00. externally triggered: True>
[2025-02-19T11:32:05.096+0000] {logging_mixin.py:190} INFO - Failure caused by name 'parsed_data' is not defined
[2025-02-19T11:32:05.096+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=pipeline, task_id=save_data, run_id=manual__2025-02-19T11:31:58.817126+00:00, execution_date=20250219T113158, start_date=20250219T113204, end_date=20250219T113205
[2025-02-19T11:32:05.108+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-19T11:32:05.108+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 892 for task save_data (name 'parsed_data' is not defined; 184)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/operators/safe_data.py", line 44, in save_data
    data.extend(parsed_data)  # Пример объединения, вам может понадобиться адаптировать логику
                ^^^^^^^^^^^
NameError: name 'parsed_data' is not defined
[2025-02-19T11:32:05.132+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-19T11:32:05.145+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-19T11:32:05.146+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
